---
title: "PreyPreferenceExp"
author: "Madelyn Hair"
date: "2023-06-14"
output: html_document
---

Load necessary packages
```{r}
library(tidyverse)
```

**Create your publication theme- diff for this plot!**
```{r}
theme_thesi <- function() {
  font <- 'Trebuchet MS' #Same as PPT
  theme_bw() %+replace%
    theme(
      
      #Gridlines
      panel.grid.major.x=element_blank(),
      panel.grid.minor.y=element_blank(),
      panel.grid.major.y = element_blank(),
      panel.grid.minor.x = element_blank(),
      axis.line = element_line(colour = "black"),
      plot.margin = margin(10,5,8,2),
      panel.border = element_blank(),
      
      #Text elements
      plot.title = element_text(family = font, 
                                size = 12, face = 'bold',
                hjust = -.2, vjust = 1.8),
      axis.title.x = element_text(family = font,
                                size = 16, margin = margin(t = 5)), 
      axis.title.y = element_text(family = font, margin= margin(r=5), angle = 90, size = 16, face = 'bold'),
      axis.text = element_text(family = font,
                               size = 10),
      axis.text.x = element_text(margin = margin(t = 0), size = 12, angle = 45, face  = NULL), 
      axis.text.y = element_text( margin = margin(r = 5), size = 10),
      legend.text = element_text(size = 10),
      legend.title = element_text(size = 12),
      
      #facet labels
      strip.text.x = element_text(size = 14, face = 'bold', family =font),
      strip.background = element_rect(fill = 'white')
    )
  
}
?margin
```

Loki Day Two, Six, and Nine, 24 hours of feeding:
```{r}
xlab = c("pre", "active", "post")
R = 3
n_clam2 = 1
n_crab2 = 2
n_hermit2 = 2
n_snail2 = 0
num_crab2 = log((R-n_crab2)/R)
num_clam2 = log((R-n_clam2)/R)
num_hermit2 = log((R-n_hermit2)/R)
num_snail2 = log((R - n_snail2)/R)
sum2 = sum(num_crab2, num_clam2, num_hermit2,num_snail2)
ma_crab2 = num_crab2/sum2
ma_snail2 = num_snail2 /sum2
ma_hermit2 = num_hermit2 / sum2
ma_clam2 = num_clam2/sum2
loki2<-tibble(ma = c(ma_clam2, ma_hermit2, ma_snail2, ma_crab2), tax = c("Clams", "Hermits", "Snails", "Crabs"), ind = ("loki"), Experimental.Day = 2)

n_clam6 = 2
n_crab6 = 0
n_hermit6 = 2
n_snail6 = 1
num_crab6 = log((R-n_crab6)/R)
num_clam6 = log((R-n_clam6)/R)
num_hermit6 = log((R-n_hermit6)/R)
num_snail6 = log((R - n_snail6)/R)
sum6 = sum(num_crab6, num_clam6, num_hermit6,num_snail6)
ma_crab6 = num_crab6 /sum6
ma_snail6 = num_snail6 /sum6
ma_hermit6 = num_hermit6 / sum6
ma_clam6 = num_clam6/sum6
loki6<-tibble(ma = c(ma_clam6, ma_hermit6, ma_snail6, ma_crab6), tax = c("Clams", "Hermits", "Snails", "Crabs"), ind = ("loki"), Experimental.Day = 6)

n_clam9 = 2
n_crab9 = 2
n_hermit9 = 1
n_snail9 = 1
num_crab9 = log((R-n_crab9)/R)
num_clam9 = log((R-n_clam9)/R)
num_hermit9 = log((R-n_hermit9)/R)
num_snail9 = log((R - n_snail9)/R)
sum9 = sum(num_crab9, num_clam9, num_hermit9,num_snail9)
ma_crab9 = num_crab9 /sum9
ma_snail9 = num_snail9 /sum9
ma_hermit9 = num_hermit9 / sum9
ma_clam9 = num_clam9/sum9
loki9<-tibble(ma = c(ma_clam9, ma_hermit9, ma_snail9, ma_crab9), tax = c("Clams", "Hermits", "Snails", "Crabs"), ind = ("loki"), Experimental.Day = 9) 

loki<- rbind(loki2,loki6,loki9)
loki <-loki%>%
  mutate(tax = factor(tax, levels = c("Hermits", "Crabs", "Clams", "Snails")), Experimental.Day = as.factor(Experimental.Day))

ylab = bquote("Manly's"~~ alpha )
lokip <- loki %>% ggplot(aes(x = Experimental.Day, y = ma, fill = tax))+
  geom_col()+
  labs(y = " ", fill = "Taxon", x = "Experimental Day", title = "A. Loki")+
    theme_thesi()+
  scale_fill_manual(values = c( "#7ADB3C","#6A8F53", "#DB9F9A", "#4E5ED9"))+ 
  scale_x_discrete(labels = xlab)+
  theme(legend.position = "none", axis.title.x = element_blank())
lokip

```

Ragnar
```{r}
R = 3
n_clam2 = 0
n_crab2 = 2
n_hermit2 = 1
n_snail2 = 1
num_crab2 = log((R-n_crab2)/R)
num_clam2 = log((R-n_clam2)/R)
num_hermit2 = log((R-n_hermit2)/R)
num_snail2 = log((R - n_snail2)/R)
sum2 = sum(num_crab2, num_clam2, num_hermit2,num_snail2)
ma_crab2 = num_crab2 /sum2
ma_snail2 = num_snail2 /sum2
ma_hermit2 = num_hermit2 / sum2
ma_clam2 = num_clam2/sum2
ragnar2<-tibble(ma = c(ma_clam2, ma_hermit2, ma_snail2, ma_crab2), tax = c("Clams", "Hermits", "Snails", "Crabs"), ind = ("ragnar"), Experimental.Day = 2)

n_clam6 = 0
n_crab6 = 2.999
n_hermit6 = 2
n_snail6 = 0
num_crab6 = log((R-n_crab6)/R)
num_clam6 = log((R-n_clam6)/R)
num_hermit6 = log((R-n_hermit6)/R)
num_snail6 = log((R - n_snail6)/R)
sum6 = sum(num_crab6, num_clam6, num_hermit6,num_snail6)
ma_crab6 = num_crab6 /sum6
ma_snail6 = num_snail6 /sum6
ma_hermit6 = num_hermit6 / sum6
ma_clam6 = num_clam6/sum6
ragnar6<-tibble(ma = c(ma_clam6, ma_hermit6, ma_snail6, ma_crab6), tax = c("Clams", "Hermits", "Snails", "Crabs"), ind = ("ragnar"), Experimental.Day = 6)

n_clam9 = 1
n_crab9 = 2.999
n_hermit9 = 1
n_snail9 = 0
num_crab9 = log((R-n_crab9)/R)
num_clam9 = log((R-n_clam9)/R)
num_hermit9 = log((R-n_hermit9)/R)
num_snail9 = log((R - n_snail9)/R)
sum9 = sum(num_crab9, num_clam9, num_hermit9,num_snail9)
ma_crab9 = num_crab9 /sum9
ma_snail9 = num_snail9 /sum9
ma_hermit9 = num_hermit9 / sum9
ma_clam9 = num_clam9/sum9
ragnar9<-tibble(ma = c(ma_clam9, ma_hermit9, ma_snail9, ma_crab9), tax = c("Clams", "Hermits", "Snails", "Crabs"), ind = ("ragnar"), Experimental.Day = 9)

ragnar<- rbind(ragnar2,ragnar6,ragnar9)
ragnar <- ragnar %>%  mutate(tax = factor(tax, levels = c("Hermits", "Crabs", "Clams", "Snails")), Experimental.Day = as.factor(Experimental.Day))

ragnarp <- ragnar %>% ggplot(aes(x = Experimental.Day, y = ma, fill = tax))+
  geom_col()+
  labs(y = ylab, fill = "Taxon", x = "Experimental Day", title = "B. Ragnar")+
    theme_thesi()+
  scale_fill_manual(values = c( "#7ADB3C","#6A8F53", "#DB9F9A", "#4E5ED9"))+
    scale_x_discrete(labels = xlab)+
  theme(legend.position = "none", axis.title.y = element_blank(),axis.title.x = element_blank())
ragnarp
```

Haliai
```{r}
R = 3
n_clam2 = 0
n_crab2 = 1
n_hermit2 = 1
n_snail2 = 0
num_crab2 = log((R-n_crab2)/R)
num_clam2 = log((R-n_clam2)/R)
num_hermit2 = log((R-n_hermit2)/R)
num_snail2 = log((R - n_snail2)/R)
sum2 = sum(num_crab2, num_clam2, num_hermit2,num_snail2)
ma_crab2 = num_crab2 /sum2
ma_snail2 = num_snail2 /sum2
ma_hermit2 = num_hermit2 / sum2
ma_clam2 = num_clam2/sum2
haliai2<-tibble(ma = c(ma_clam2, ma_hermit2, ma_snail2, ma_crab2), tax = c("Clams", "Hermits", "Snails", "Crabs"), ind = ("haliai"), Experimental.Day = 2)

n_clam6 = 0
n_crab6 = 2.999
n_hermit6 = 1
n_snail6 = 0
num_crab6 = log((R-n_crab6)/R)
num_clam6 = log((R-n_clam6)/R)
num_hermit6 = log((R-n_hermit6)/R)
num_snail6 = log((R - n_snail6)/R)
sum6 = sum(num_crab6, num_clam6, num_hermit6,num_snail6)
ma_crab6 = num_crab6 /sum6
ma_snail6 = num_snail6 /sum6
ma_hermit6 = num_hermit6 / sum6
ma_clam6 = num_clam6/sum6
haliai6<-tibble(ma = c(ma_clam6, ma_hermit6, ma_snail6, ma_crab6), tax = c("Clams", "Hermits", "Snails", "Crabs"), ind = ("haliai"), Experimental.Day = 6)

n_clam9 = 2
n_crab9 = 2
n_hermit9 = 1
n_snail9 = 0
num_crab9 = log((R-n_crab9)/R)
num_clam9 = log((R-n_clam9)/R)
num_hermit9 = log((R-n_hermit9)/R)
num_snail9 = log((R - n_snail9)/R)
sum9 = sum(num_crab9, num_clam9, num_hermit9,num_snail9)
ma_crab9 = num_crab9 /sum9
ma_snail9 = num_snail9 /sum9
ma_hermit9 = num_hermit9 / sum9
ma_clam9 = num_clam9/sum9
haliai9<-tibble(ma = c(ma_clam9, ma_hermit9, ma_snail9, ma_crab9), tax = c("Clams", "Hermits", "Snails", "Crabs"), ind = ("haliai"), Experimental.Day = 9)

haliai<- rbind(haliai2,haliai6,haliai9)
haliai <- haliai %>%mutate(tax = factor(tax, levels = c("Hermits", "Crabs", "Clams", "Snails")), Experimental.Day = as.factor(Experimental.Day))

haliaip <- haliai %>% ggplot(aes(x = Experimental.Day, y = ma, fill = tax))+
  geom_col()+
  labs(y = ylab, fill = "Taxon", title = "C. Haliai", x = "Experimental Day")+
    theme_thesi()+
  scale_fill_manual(values = c( "#7ADB3C","#6A8F53", "#DB9F9A", "#4E5ED9"))+
    scale_x_discrete(labels = xlab)+
  theme(axis.title.y = element_blank(),axis.title.x = element_blank())
haliaip
```

Caly
```{r}
R = 3
n_clam2 = 1
n_crab2 = 2.999
n_hermit2 = 1
n_snail2 = 1
num_crab2 = log((R-n_crab2)/R)
num_clam2 = log((R-n_clam2)/R)
num_hermit2 = log((R-n_hermit2)/R)
num_snail2 = log((R - n_snail2)/R)
sum2 = sum(num_crab2, num_clam2, num_hermit2,num_snail2)
ma_crab2 = num_crab2 /sum2
ma_snail2 = num_snail2 /sum2
ma_hermit2 = num_hermit2 / sum2
ma_clam2 = num_clam2/sum2
caly2<-tibble(ma = c(ma_clam2, ma_hermit2, ma_snail2, ma_crab2), tax = c("Clams", "Hermits", "Snails", "Crabs"), ind = ("caly"), Experimental.Day = 2)

n_clam6 = 0
n_crab6 = 2
n_hermit6 = 1
n_snail6 = 0
num_crab6 = log((R-n_crab6)/R)
num_clam6 = log((R-n_clam6)/R)
num_hermit6 = log((R-n_hermit6)/R)
num_snail6 = log((R - n_snail6)/R)
sum6 = sum(num_crab6, num_clam6, num_hermit6,num_snail6)
ma_crab6 = num_crab6 /sum6
ma_snail6 = num_snail6 /sum6
ma_hermit6 = num_hermit6 / sum6
ma_clam6 = num_clam6/sum6
caly6<-tibble(ma = c(ma_clam6, ma_hermit6, ma_snail6, ma_crab6), tax = c("Clams", "Hermits", "Snails","Crabs"), ind = ("caly"), Experimental.Day = 6)

n_clam9 = 1
n_crab9 = 2.999
n_hermit9 = 1
n_snail9 = 1
num_crab9 = log((R-n_crab9)/R)
num_clam9 = log((R-n_clam9)/R)
num_hermit9 = log((R-n_hermit9)/R)
num_snail9 = log((R - n_snail9)/R)
sum9 = sum(num_crab9, num_clam9, num_hermit9,num_snail9)
ma_crab9 = num_crab9 /sum9
ma_snail9 = num_snail9 /sum9
ma_hermit9 = num_hermit9 / sum9
ma_clam9 = num_clam9/sum9
caly9<-tibble(ma = c(ma_clam9, ma_hermit9, ma_snail9, ma_crab9), tax = c("Clams", "Hermits", "Snails", "Crabs"), ind = ("caly"), Experimental.Day = 9)


caly<- rbind(caly2,caly6,caly9)
caly <- caly %>%mutate(tax = factor(tax, levels = c("Hermits", "Crabs", "Clams", "Snails")), Experimental.Day = as.factor(Experimental.Day))

calyp <- caly %>% ggplot(aes(x = Experimental.Day, y = ma, fill = tax))+
  geom_col()+
  labs(y = " ", fill = "Taxon", title = "D. Calypso", x = "Experimental Day")+
  scale_fill_manual(values = c( "#7ADB3C","#6A8F53", "#DB9F9A", "#4E5ED9"))+ 
    theme_thesi()+
    scale_x_discrete(labels = xlab)+
  theme(legend.position = "none",axis.title.x = element_blank())
calyp
```

Selkie
```{r}
R = 3
n_clam2 = 1
n_crab2 = 1
n_hermit2 = 2
n_snail2 = 0
num_crab2 = log((R-n_crab2)/R)
num_clam2 = log((R-n_clam2)/R)
num_hermit2 = log((R-n_hermit2)/R)
num_snail2 = log((R - n_snail2)/R)
sum2 = sum(num_crab2, num_clam2, num_hermit2,num_snail2)
ma_crab2 = num_crab2 /sum2
ma_snail2 = num_snail2 /sum2
ma_hermit2 = num_hermit2 / sum2
ma_clam2 = num_clam2/sum2
selkie2<-tibble(ma = c(ma_clam2, ma_hermit2, ma_snail2, ma_crab2), tax = c("Clams", "Hermits", "Snails","Crabs"), ind = ("selkie"), Experimental.Day = 2)

n_clam6 = 2.999
n_crab6 = 1
n_hermit6 = 1
n_snail6 = 0
num_crab6 = log((R-n_crab6)/R)
num_clam6 = log((R-n_clam6)/R)
num_hermit6 = log((R-n_hermit6)/R)
num_snail6 = log((R - n_snail6)/R)
sum6 = sum(num_crab6, num_clam6, num_hermit6,num_snail6)
ma_crab6 = num_crab6 /sum6
ma_snail6 = num_snail6 /sum6
ma_hermit6 = num_hermit6 / sum6
ma_clam6 = num_clam6/sum6
selkie6<-tibble(ma = c(ma_clam6, ma_hermit6, ma_snail6, ma_crab6), tax = c("Clams", "Hermits", "Snails", "Crabs"), ind = ("selkie"), Experimental.Day = 6)

n_clam9 = 1
n_crab9 = 2.999
n_hermit9 = 0
n_snail9 = 0
num_crab9 = log((R-n_crab9)/R)
num_clam9 = log((R-n_clam9)/R)
num_hermit9 = log((R-n_hermit9)/R)
num_snail9 = log((R - n_snail9)/R)
sum9 = sum(num_crab9, num_clam9, num_hermit9,num_snail9)
ma_crab9 = num_crab9 /sum9
ma_snail9 = num_snail9 /sum9
ma_hermit9 = num_hermit9 / sum9
ma_clam9 = num_clam9/sum9
selkie9<-tibble(ma = c(ma_clam9, ma_hermit9, ma_snail9, ma_crab9), tax = c("Clams", "Hermits", "Snails", "Crabs"), ind = ("selkie"), Experimental.Day = 9)

selkie<- rbind(selkie2,selkie6,selkie9)
selkie <- selkie %>%mutate(tax = factor(tax, levels = c("Hermits", "Crabs", "Clams", "Snails")), Experimental.Day = as.factor(Experimental.Day))

selkiep <- selkie %>% ggplot(aes(x = Experimental.Day, y = ma, fill = tax))+
  geom_col()+
  labs(y = ylab, fill = "Taxon", title = "E. Selkie", x = " ")+
  theme_thesi()+
  scale_fill_manual(values = c( "#7ADB3C","#6A8F53", "#DB9F9A", "#4E5ED9"))+ 
    scale_x_discrete(labels = xlab)+
  theme(legend.position = "none", axis.title.y = element_blank(), axis.title.x = element_text(size = 16))
selkiep
```

Scylla
```{r}
R = 3
n_clam2 = 1
n_crab2 = 0
n_hermit2 = 1
n_snail2 = 0
num_crab2 = log((R-n_crab2)/R)
num_clam2 = log((R-n_clam2)/R)
num_hermit2 = log((R-n_hermit2)/R)
num_snail2 = log((R - n_snail2)/R)
sum2 = sum(num_crab2, num_clam2, num_hermit2,num_snail2)
ma_crab2 = num_crab2 /sum2
ma_snail2 = num_snail2 /sum2
ma_hermit2 = num_hermit2 / sum2
ma_clam2 = num_clam2/sum2
scylla2<-tibble(ma = c(ma_clam2, ma_hermit2, ma_snail2, ma_crab2), tax = c("Clams", "Hermits", "Snails", "Crabs"), ind = ("scylla"), Experimental.Day = 2)

n_clam6 = 0
n_crab6 = 2
n_hermit6 = 1
n_snail6 = 0
num_crab6 = log((R-n_crab6)/R)
num_clam6 = log((R-n_clam6)/R)
num_hermit6 = log((R-n_hermit6)/R)
num_snail6 = log((R - n_snail6)/R)
sum6 = sum(num_crab6, num_clam6, num_hermit6,num_snail6)
ma_crab6 = num_crab6 /sum6
ma_snail6 = num_snail6 /sum6
ma_hermit6 = num_hermit6 / sum6
ma_clam6 = num_clam6/sum6
scylla6<-tibble(ma = c(ma_clam6, ma_hermit6, ma_snail6, ma_crab6), tax = c("Clams", "Hermits", "Snails", "Crabs"), ind = ("scylla"), Experimental.Day = 6)

n_clam9 = 0
n_crab9 = 2.999
n_hermit9 = 0
n_snail9 = 0
num_crab9 = log((R-n_crab9)/R)
num_clam9 = log((R-n_clam9)/R)
num_hermit9 = log((R-n_hermit9)/R)
num_snail9 = log((R - n_snail9)/R)
sum9 = sum(num_crab9, num_clam9, num_hermit9,num_snail9)
ma_crab9 = num_crab9 /sum9
ma_snail9 = num_snail9 /sum9
ma_hermit9 = num_hermit9 / sum9
ma_clam9 = num_clam9/sum9
scylla9<-tibble(ma = c(ma_clam9, ma_hermit9, ma_snail9, ma_crab9), tax = c("Clams", "Hermits", "Snails", "Crabs"), ind = ("scylla"), Experimental.Day = 9)

scylla<- rbind(scylla2,scylla6,scylla9)
scylla <- scylla %>%mutate(tax = factor(tax, levels = c("Hermits", "Crabs", "Clams", "Snails")), Experimental.Day = as.factor(Experimental.Day))
scyllap <- scylla %>% ggplot(aes(x = Experimental.Day, y = ma, fill = tax))+
  geom_col()+
  labs(y = " ", fill = "Taxon", title = "F. Scylla", x = "Experimental Day")+
  theme_thesi()+
  scale_fill_manual(values = c( "#7ADB3C","#6A8F53", "#DB9F9A", "#4E5ED9")) + 
    scale_x_discrete(labels = xlab)+
  theme(legend.position = "none", axis.title.y = element_blank(),axis.title.x = element_blank())
scyllap
```

```{r}
library(patchwork)
patch <- lokip + ragnarp + haliaip + calyp + selkiep + scyllap + plot_layout(nrow = 2)
patch 
ggsave("graphics/preypreference_exp.jpg", height = 4, width = 6.5, units = 'in')
#ggsave("graphics/PPT/preypreference_exp.jpg", width = 8, height = 4.8, units = 'in')

```




